
[server]
	#If true, enables camera recoil when firing a weapon
	enableCameraRecoil = true

	#Stun Grenade related properties
	[server.grenade]
		#Volume of the ringing sound when deafened will play at this volume, before eventually fading to 0.
		#Range: 0.0 ~ 1.0
		ringVolume = 1.0
		#Transparency of the overlay when blinded will be this alpha value, before eventually fading to 0 alpha.
		#Range: > 0
		alphaFadeThreshold = 40
		#After the duration drops to this many ticks, the transparency of the overlay when blinded will gradually fade to 0 alpha.
		#Range: 0 ~ 255
		alphaOverlay = 255
		#After the duration drops to this many ticks, the ringing volume will gradually fade to 0 and other sound volumes will fade back to %100.
		#Range: > 0
		soundFadeThreshold = 90
		#Volume of most game sounds when deafened will play at this percent, before eventually fading back to %100.
		#Range: 0.0 ~ 1.0
		soundPercentage = 0.05

		#Properties relating to grenades
		[server.grenade.grenades]
			#The max distance which the explosion is effective to
			#Range: 0.0 ~ 1.7976931348623157E308
			explosionRadius = 2.0

		#Development
		[server.grenade.development]
			#If enabled any crosshair will continue to render on aim.
			permanentCrosshair = false
			#If enabled, /t dev will both be registered (Upon restart), and function! Used as well to speed up tag checks
			enableTDev = false
			#Whether the shooters bullets can harm the shooter, great for testing armor and on hit effects with the development gun
			bulletSelfHarm = false
			#Directory to build all TaC sub-directories, these will contain export data from /t dev functions
			tDevPath = ""

		#Properties relating to stun grenades
		[server.grenade.stun_grenades]

			#Blinding properties of stun grenades
			[server.grenade.stun_grenades.blind]
				#If true, hostile mobs will be unable to target entities while they are blinded by a stun grenade.
				blindMobs = true

				[server.grenade.stun_grenades.blind.effect_criteria]
					#Effect will have this duration (in ticks) if the grenade is directly at the player's eyes while looking directly at it.
					#Range: > 0
					durationMax = 220
					#Angle between the eye/looking direction and the eye/grenade direction must be no more than half this many degrees to have an effect.
					#Range: 0.0 ~ 360.0
					angleEffect = 170.0
					#If true, the effect is only applied if the line between the eyes and the grenade does not intersect any non-liquid blocks with an opacity greater than 0.
					raytraceOpaqueBlocks = true
					#Grenade must be no more than this many meters away to have an effect.
					#Range: 0.0 ~ 1.7976931348623157E308
					radius = 15.0
					#After duration is attenuated by distance, it will be further attenuated depending on the angle (in degrees) between the eye/looking direction and the eye/grenade direction. This is done by multiplying it by 1 (no attenuation) if the angle is 0; and by this value if the angle is the maximum within the angle of effect.
					#Range: 0.0 ~ 1.0
					angleAttenuationMax = 0.75
					#Effect will have this duration (in ticks) if the grenade is the maximum distance from the player's eyes while looking directly at it.
					#Range: > 0
					durationMin = 10

			#Deafening properties of stun grenades
			[server.grenade.stun_grenades.deafen]
				#If true, peaceful mobs will panic upon being deafened by a stun grenade.
				panicMobs = true

				[server.grenade.stun_grenades.deafen.effect_criteria]
					#Effect will have this duration (in ticks) if the grenade is directly at the player's eyes while looking directly at it.
					#Range: > 0
					durationMax = 280
					#Angle between the eye/looking direction and the eye/grenade direction must be no more than half this many degrees to have an effect.
					#Range: 0.0 ~ 360.0
					angleEffect = 360.0
					#If true, the effect is only applied if the line between the eyes and the grenade does not intersect any non-liquid blocks with an opacity greater than 0.
					raytraceOpaqueBlocks = false
					#Grenade must be no more than this many meters away to have an effect.
					#Range: 0.0 ~ 1.7976931348623157E308
					radius = 15.0
					#After duration is attenuated by distance, it will be further attenuated depending on the angle (in degrees) between the eye/looking direction and the eye/grenade direction. This is done by multiplying it by 1 (no attenuation) if the angle is 0; and by this value if the angle is the maximum within the angle of effect.
					#Range: 0.0 ~ 1.0
					angleAttenuationMax = 0.75
					#Effect will have this duration (in ticks) if the grenade is the maximum distance from the player's eyes while looking directly at it.
					#Range: > 0
					durationMin = 100

		#Properties relating to mob aggression
		[server.grenade.aggro_mobs]
			#If true, in addition to causing peaceful mobs to panic, firing a gun will also cause nearby hostile mobs to target the shooter.
			angerHostileMobs = true
			#Any mobs of defined will not aggro on shooters
			exemptMobs = []
			#Any mobs within a sphere of this radius will aggro on the shooter of an unsilenced gun.
			#Range: 0.0 ~ 1.7976931348623157E308
			unsilencedRange = 20.0
			#If true, nearby mobs are angered and/or scared by the firing of guns.
			enabled = true

		#Properties relating to missiles (no use now)
		[server.grenade.missiles]
			#The max distance which the explosion is effective to
			#Range: 0.0 ~ 1.7976931348623157E308
			explosionRadius = 1.0

		#Properties relating to projectile spread
		[server.grenade.projectile_spread]
			#Weapon grows more inaccurate depending if the player is in motion (Forward, Strafing, Jumping)
			movementInaccuracy = true

		#Properties relating to gameplay
		[server.grenade.gameplay]
			#True if you want to have unlimited current ammo in creative mode.
			creativeUnlimitedCurrentAmmo = true
			#Force camera shake on for all players, since control over the weapon is reduced with this off, having a client only options could lead to balance issues.
			forceCameraShakeOnFire = false
			#Enables the check for head shots for players. Projectiles that hit the head of a player will have increased damage.
			enableHeadShots = true
			#If enable, Fire Starter will cause fire (ignite the block)
			fireStarterCauseFire = false
			#If enable, allows guns to shoot out glass
			enableGunGriefing = true
			#The value to multiply the damage by if projectile hit the players head
			#Range: 1.0 ~ 1.7976931348623157E308
			headShotDamageMultiplier = 2.0
			#If true, improves the accuracy of weapons by considering the ping of the player. This has no affect on singleplayer. This will add a little overhead if enabled.
			improvedHitboxes = true
			#True if you want to see the laser beam from a third-person perspective.
			canSeeLaserThirdSight = true
			#Enable rendering of TaC armor on the player, useful if other armors are taking priority, doesn't fit gameplay theme, or not performant enough.
			renderTaCArmor = true
			#Bullets completely ignore Minecraft armor, forcing you to use our armor system.
			bulletsIgnoreStandardArmor = true
			#Adjust decelerate the player or mob when they are on fire caused by tac.
			#Range: 0.0 ~ 1.0
			decelerationFromTacIgnite = 0.3
			#True if you don't want to hurt players.
			gunOfKindnessToPlayer = false
			#True if you want to have unlimited current ammo in survival or adventure mode.
			commonUnlimitedCurrentAmmo = false
			#If enable, allows guns to remove blocks on explosions
			enableExplosionBreak = false
			#Adjust the spread of the gun when the player is ducking.
			#Range: 0.0 ~ 1.0
			duckSpreadPercent = 0.75
			#If true, projectiles will cause knockback when an entity is hit. By default this is set to true to match the behaviour of Minecraft.
			enableKnockback = true
			#True if you want to have unlimited reserve ammo in creative mode.
			creativeUnlimitedReserveAmmo = true
			#The percent of the damage ignore the armor, 0 = Minecraft armor effectiveness doesn't change, 1 = Minecraft armor never effects bullet damage.
			#Range: 0.0 ~ 1.0
			percentDamageIgnoresStandardArmor = 0.5
			#If enable, explosion will cause fire (ignite the block)
			explosionCauseFire = false
			#True if you want to have unlimited reserve ammo in survival or adventure mode.
			commonUnlimitedReserveAmmo = false
			#True if you don't want to hurt any mobs.
			gunOfKindness = false
			#If true, projectiles will ignore leaves when checking for collision
			ignoreLeaves = true
			#The extra amount to expand an entity's bounding box when checking for projectile collision. Setting this value higher will make it easier to hit entities
			#Range: 0.0 ~ 1.0
			growBoundingBoxAmountV2 = 0.0
			#True if you don't want to use level system.
			lockGunLevel = false
			#All weapons have a percentage of damage applied, no matter the class match up, false means blunt damage is never applied before armor calc.
			armorBluntDamage = true
			#If lockGunLevel true, which level will it be locked.
			#Range: 1 ~ 10
			lockLevelOfGun = 1
			#The value to multiply the damage by if projectile is a critical hit
			#Range: 1.0 ~ 1.7976931348623157E308
			criticalDamageMultiplier = 2.0
			#Sets the strength of knockback when shot by a bullet projectile. Knockback must be enabled for this to take effect. If value is equal to zero, knockback will use default minecraft value
			#Range: 0.0 ~ 1.0
			knockbackStrength = 0.15

	#Audio properties
	[server.audio]
		#The maximum distance weapons can be heard by players.
		#Range: 0.0 ~ 1.7976931348623157E308
		gunShotMaxDistance = 100.0
		#The maximum distance barrel whine can be heard by players.
		#Range: 0.0 ~ 1.7976931348623157E308
		gunBarrelMaxDistance = 24.0

